@MediatRTest.Api_HostAddress = https://localhost:7251

### Get invoices

GET {{MediatRTest.Api_HostAddress}}/api/v1/invoices
Accept: application/json

### Get invoice by id

GET {{MediatRTest.Api_HostAddress}}/api/v1/invoices/0c14cfbd-e8ff-4dba-8931-2d4e7a1f32df
Accept: application/json

### Creates a new invoice

POST {{MediatRTest.Api_HostAddress}}/api/v1/invoices
Content-Type: application/json

{
  "invoiceNumber": "FV/101/2024",
  "amount": 100,
  "invoiceDate": "2024-08-18T10:52:10.610Z",
  "dueDate": "2024-09-18T10:52:10.610Z",
  "currency": "USD",
  "customer": {
    "name": "Customer 10",
    "address": "Address 5"
  },
  "items": [
    {
      "description": "Item 1",
      "amount": 20,
      "quantity": 2
    },
    {
      "description": "Item 2",
      "amount": 60,
      "quantity": 1
    }
  ]
}

### Deletes an invoice

DELETE {{MediatRTest.Api_HostAddress}}/api/v1/invoices/53f01af2-c34e-445d-bede-bab457f9a24c
Accept: application/json
